### ISSUE TITLE
Fireflies

### ISSUE THREAD

**Issue by Domenicobrz** [hoverinc/ray-tracing-renderer#12]
First of all: thank you for your amazing work, this renderer is amazing!

I've noticed that it's easy to get fireflies while rendering:

![Annotazione 2019-09-15 184817](https://user-images.githubusercontent.com/25647854/64924866-65fde280-d7e9-11e9-8d64-04bd80742989.jpg)

Is there a way to mitigate the problem or to limit the maximum amount of radiance received at a pixel?

**Comment by jaxry** [comment]
Thanks for the ticket! 

>Is there a way to mitigate the problem or to limit the maximum amount of radiance received at a pixel?

Unfortunately, not at the moment. The half-solution would be to reduce the number of smooth and specular surfaces in your scene. Those fireflies in particular are caused by specular highlights. Blender's documentation has a great overview of the [problem](https://docs.blender.org/manual/en/latest/render/cycles/optimizations/reducing_noise.html#caustics-and-filter-glossy) and a proper solution.

Those fireflies appear when diffuse surfaces occasionally reflect specular parts of another surface. Technically speaking, those fireflies are physically correct, but they won't stop appearing as noise until thousands of samples later, which is impractical in our case. Blender's solution to the problem is to introduce a _filter glossy_ option.

Filter glossy increases increases surface roughness in secondary scattering events following a diffuse reflection. This allows the path tracer to find contributions for indirect bounces by connecting to the light source even with highly glossy materials.

That's a solution we could explore since it wouldn't be too tricky to implement right now, if you or anybody else would be interested to explore that path. 

The other solution involves introducing a denoiser which removes all noise and fireflies altogether. That's what https://github.com/hoverinc/ray-tracing-renderer/issues/2 describes. I'm currently working on an implementation, but it's several weeks out.

**Comment by Domenicobrz** [comment]
Thank you for your help! I'll probably use a simple denoiser for the moment, that should do it
thanks again!
