### ISSUE TITLE
ES6 module not working

### ISSUE THREAD

**Issue by ricardomatias** [hoverinc/ray-tracing-renderer#20]
Error: `export 'EnvironmentLight' (imported as 'THREE') was not found in 'three'`

It's not working with `npm install` using ES6 modules. As far as I see, your `main.js` is not being imported anywhere which doesn't expose the rest of the modules.

**Comment by jaxry** [comment]
Thanks for the ticket. The npm package is definitely not configured correctly... It looks like the `main` field in the [package.json](https://github.com/hoverinc/ray-tracing-renderer/blob/master/package.json) isn't pointing to the right file. If you navigate to the dependency in your `node_modules` folder, and change that property to `src/main.js`, does the environment light import then?

If that takes care of it, would you like to submit a PR with the change? If it's too much trouble, I can take care of it all the same too 👍

**Comment by jaxry** [comment]
I believe I've addressed the problem in the latest version. If it's still an issue, let me know and we can try figuring it out.

**Comment by ricardomatias** [comment]
I'm getting the error `THREE is not defined` at `child instanceof THREE.EnvironmentLight` from `RayTracingShader.js`

I've actually spent quite a bit of time playing around with rollup's config and imports and I didn't manage to make it work. I suspect it has something to do with the way things are imported. There are examples of using the global/window `three` instance but there are also occasions where the import version is used.

Unrelated, the keyword `module` should also not be used (as in `RayTracingRenderer.js`) since it might create conflicts.

**Comment by jaxry** [comment]
Thanks for looking into this. I'm not sure why you're getting that error from [RayTracingShader](https://github.com/hoverinc/ray-tracing-renderer/blob/master/src/renderer/RayTracingShader.js), since `three` is imported in that file. Rollup is configured so that three.js should be included in the HTML before the code that contains the ray tracing renderer. Are you doing that? If so, the issue is deeper.

>Unrelated, the keyword module should also not be used (as in RayTracingRenderer.js) since it might create conflicts.

That's a good point. Taking a peek at the [build file](https://github.com/hoverinc/ray-tracing-renderer/blob/master/build/RayTracingRenderer.js), and `module` is used by the build. But it's only used outside the ray tracing renderer's usage of the variable, and will be kept separate via scoping. Maybe it's a good idea to change it anyway? But I don't see an immediate problem.

**Comment by elfrank** [comment]
Hi @ricardomatias , thanks for reporting this issue.

If it's not too much to ask, could you provide an example where we can reproduce this issue? https://codepen.io might be a good option. This would help us to identify the source of the problem.

Thanks!

**Comment by elfrank** [comment]
@ricardomatias could you try version `0.1.4`? does that fix the issue?

**Comment by ricardomatias** [comment]
Yes, it's working!

**Comment by elfrank** [comment]
@ricardomatias excellent! thanks! 👍
