### ISSUE TITLE
Fantastic project

### ISSUE THREAD

**Issue by VinAr22** [hoverinc/ray-tracing-renderer#45]
Hi! Great project!!! I do like it! I hope you succeed.

**Comment by VinAr22** [comment]
Is it possible to use all features of MeshStandardMaterial? Like roughness, bumpMap, refraction and so on?

**Comment by jaxry** [comment]
Glad you like the project!

MeshStandardMaterial is only partially supported for the time being.  The supported properties are:
`map`
`metalness`
`normalMap`
`normalScale`
`roughness`
`roughnessMap`

Emission and emissive maps would be really cool to support since light-emitting objects would add global illumination to the scene with path tracing. The path tracing algorithm already handles emission in theory, so it's just a matter of passing the relevant maps to the shader and adding a few supporting lines of shader code. I can make a ticket describing the necessary process.

**Comment by VinAr22** [comment]
Thank you for quick response! Sorry, im not good in shader coding. Maybe you add support emissive, bump, alpha in future?

**Comment by VinAr22** [comment]
Hi! I`m trying to use depth of field in new version of renderer, but its not working... Is it deprecated? Thanks!

**Comment by jaxry** [comment]
Depth of field broke with the recent addition of temporal filtering. Sorry about that! The two techniques are incompatible, so depth-of-field will have to be done via a post-processing pass in the future. I'll update the docs to reflect this change.

**Comment by VinAr22** [comment]
Oh, ok. Thank you for your reply!
