### ISSUE TITLE
Dull texture with same lighting

### ISSUE THREAD

**Issue by ManishJu** [hoverinc/ray-tracing-renderer#88]
It feels like texture contrast takes heavy hit when we change from threejs's WebGL2 to raytracing-renderer. What could be the issue ? The following textures have same lighting conditions but the dull one is from the raytracing-renderer. I even waited for the renderer to go on for 10 minutes so that the texture might clear out but the results are almost same.

I checked the texture encoding when shifting from threejs's renderer to raytracing renderer, they are same. Is that taken into account in raytracing renderer as srgb-encoding should be default for pictures on web
.

![Screenshot from 2020-05-04 18-03-32](https://user-images.githubusercontent.com/24234466/80993449-fb122200-8e32-11ea-838b-305f598278bc.png)
![Screenshot from 2020-05-04 18-04-08](https://user-images.githubusercontent.com/24234466/80993451-fbaab880-8e32-11ea-9693-04df897323d8.png)

Thanks!

**Comment by jaxry** [comment]
I'm not sure what's going on here. For starters, both renderers do srgb gamma correction so that isn't the issue directly. Are both renderers using the same tone mapping? What about lighting?

**Comment by ManishJu** [comment]
Yes both of them have same lighting and both of them are using ACES filmic tone mapping.

**Comment by ManishJu** [comment]
Could it be the texture minification/magnification filter ?

**Comment by ManishJu** [comment]
Sorry I did not provide the original texture for you guys to test . Here you go :
![Casa Catillo](https://user-images.githubusercontent.com/24234466/81022370-5957f880-8e65-11ea-995d-4fef38c04662.jpg)

**Comment by jaxry** [comment]
This is a really tricky one to debug since it's difficult to control the differences between Three.js and this renderer. I have a few ideas:

* Dir lights are not normalized between Three.js and this renderer. The brightnesses are different, and that could be one looks lighter than the other. This is a limitation that needs to be addressed outside of this issue, but it could be contributing to it. Do the brightnesses "look" the same elsewhere in the scene?

* The renderer's BRDF is slightly different than Three.js's. Three.js simply adds the diffuse and specular light components together, while this renderer implements Disney's Principled BRDF. This could be making the surface reflect more light. To debug this, temporarily changing the BRDF to the one Three.js uses could confirm the issue.

Texture filtering _could_ maybe be an issue but I don't understand how that would happen. If you could replicate the bug with a simple test scene that you could share, I could look into it and help out. Does that sound possible?

**Comment by ManishJu** [comment]
Thanks for replying !. I will definitely post a  piece of code to replicate the bug here soon.

**Comment by ManishJu** [comment]
I think I need to get clear of this issue before I can proceed : #95

**Comment by ManishJu** [comment]
There is this difference in the original image and when the put inside the ray tracer. The original image is same when rendered in realtime.

**Comment by jaxry** [comment]
This is most unusual. Does the texture look darker on my machine to you? It looks as black to me as the source image.
![Screenshot from 2020-05-12 12-35-12](https://user-images.githubusercontent.com/4411068/81737542-1a213d00-944d-11ea-8fd0-0a3cc56a08c3.png)

I think this could be a driver bug on your machine related to gamma correction. Would you be able to try this out:

1. https://github.com/hoverinc/ray-tracing-renderer/blob/master/src/renderer/MaterialBuffer.js#L31
Set the third argument from `true` to `false`. This will disable sRGB gamma correction

2. https://github.com/hoverinc/ray-tracing-renderer/blob/master/src/renderer/glsl/chunks/materialBuffer.glsl#L42
And replace this line with these two lines to do gamma correction manually.
```
      vec3 texColor = texture(diffuseMap, vec3(uv * materials.diffuseNormalMapSize[diffuseMapIndex].xy, diffuseMapIndex)).rgb;
      color *= pow(texColor, vec3(2.2));
```

Does that solve the issue?

>PS: the webgl-comparison scene inside the scenes folder is also broken . Should I make a separate issue for this ?

Did you try localhost:8080/scenes/webgl-comparison/dev.html? dev.html (instead of index.html) is needed for local viewing.

**Comment by ManishJu** [comment]
Hello @jaxry !,
Thanks for answering my questions. I tried the above with multiple operating systems(Ubuntu,Windows) & multiple nvidia driver versions namely 330,335 and 340. I even got a chance to get the results from a Mac running on  integrated card. The results were all same ! Your results are quite different as compared to ours. Now I doubt which one is correct.  What more can be done ?

For webgl-comparison. I will try with your suggestion and it worked . Thanks !

**Comment by ManishJu** [comment]
I guess the GGX model of Disney has a heavy influence(lobe) of diffuse lighting. That being said I was able to get to good texture while reducing my texture metalness from 0.2 to 0.0 which is not a big leap in realtime but affects the ray-tracer a lot. Thanks for your time guys . :)
